---
- hosts: webservers
  remote_user: root
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  tasks:
  - name: install nginx
    apt:
      pkg: nginx
      state: present
  - name: make directory for site
    file:
      path: /var/apps/book.vincecima.com
      state: directory
      mode: 0755
  - name: deploy index
    copy:
      src: index.html
      dest: /var/apps/book.vincecima.com/index.html
  - name: deploy nginx configuration for site
    copy:
      src: book.vincecima.com.conf
      dest: /etc/nginx/sites-available/book.vincecima.com.conf
      mode: 0640
  - name: link book.vincecima.com.conf into sites-enabled
    file:
      src: /etc/nginx/sites-available/book.vincecima.com.conf
      dest: /etc/nginx/sites-enabled/book.vincecima.com.conf
      state: link
    notify:
      - restart nginx